import type {
  EffectPreset,
  SocialShareConfig,
  VideoAspectRatio,
  MusicTrack,
  VideoTemplate,
  MemeTemplate,
} from "@/types";

export const EFFECT_PRESETS: {
  id: EffectPreset;
  label: string;
  emoji: string;
  description: string;
}[] = [
  {
    id: "explode",
    label: "Explode",
    emoji: "💥",
    description: "Burst into dramatic fragments",
  },
  {
    id: "melt",
    label: "Melt",
    emoji: "🫠",
    description: "Drip and flow like liquid",
  },
  {
    id: "inflate",
    label: "Inflate",
    emoji: "🎈",
    description: "Balloon up and bounce",
  },
  {
    id: "freeze",
    label: "Freeze",
    emoji: "🧊",
    description: "Ice crystals spreading",
  },
  {
    id: "dissolve",
    label: "Dissolve",
    emoji: "✨",
    description: "Sparkle into particles",
  },
  {
    id: "transform",
    label: "Transform",
    emoji: "🦋",
    description: "Morph into something new",
  },
  {
    id: "glitch",
    label: "Glitch",
    emoji: "📺",
    description: "Digital distortion vibes",
  },
  {
    id: "rainbow",
    label: "Rainbow",
    emoji: "🌈",
    description: "Colorful wave wash",
  },
  {
    id: "pixelate",
    label: "Pixelate",
    emoji: "👾",
    description: "Retro pixel breakdown",
  },
  {
    id: "neon",
    label: "Neon",
    emoji: "💡",
    description: "Glowing neon outlines",
  },
];

export const SOCIAL_CONFIGS: Record<SocialPlatform, SocialShareConfig> = {
  tiktok: {
    platform: "tiktok",
    aspectRatio: "9:16",
    maxDuration: 60,
    label: "TikTok",
    icon: "smartphone",
    color: "#000000",
    dimensions: { width: 1080, height: 1920 },
  },
  instagram: {
    platform: "instagram",
    aspectRatio: "1:1",
    maxDuration: 60,
    label: "Instagram",
    icon: "instagram",
    color: "#E4405F",
    dimensions: { width: 1080, height: 1080 },
  },
  youtube: {
    platform: "youtube",
    aspectRatio: "16:9",
    maxDuration: 120,
    label: "YouTube",
    icon: "youtube",
    color: "#FF0000",
    dimensions: { width: 1920, height: 1080 },
  },
  twitter: {
    platform: "twitter",
    aspectRatio: "16:9",
    maxDuration: 140,
    label: "X / Twitter",
    icon: "twitter",
    color: "#1DA1F2",
    dimensions: { width: 1920, height: 1080 },
  },
};

import type { SocialPlatform } from "@/types";

export const ASPECT_RATIOS: {
  value: VideoAspectRatio;
  label: string;
  icon: string;
}[] = [
  { value: "9:16", label: "Vertical", icon: "📱" },
  { value: "1:1", label: "Square", icon: "⬜" },
  { value: "16:9", label: "Landscape", icon: "🖥️" },
  { value: "4:5", label: "Portrait", icon: "📷" },
];

export const DURATION_OPTIONS = [3, 5, 10, 15, 30, 60];

export const SAMPLE_MUSIC_TRACKS: MusicTrack[] = [
  {
    id: "track-1",
    title: "Electric Dreams",
    artist: "SynthWave",
    duration: 30,
    bpm: 128,
    genre: "Electronic",
    previewUrl: "/audio/electric-dreams-preview.mp3",
    fullUrl: "/audio/electric-dreams.mp3",
    isTrending: true,
  },
  {
    id: "track-2",
    title: "Sunset Vibes",
    artist: "ChillHop",
    duration: 45,
    bpm: 95,
    genre: "Lo-fi",
    previewUrl: "/audio/sunset-vibes-preview.mp3",
    fullUrl: "/audio/sunset-vibes.mp3",
    isTrending: true,
  },
  {
    id: "track-3",
    title: "Bass Drop",
    artist: "BeatMaker",
    duration: 15,
    bpm: 150,
    genre: "Trap",
    previewUrl: "/audio/bass-drop-preview.mp3",
    fullUrl: "/audio/bass-drop.mp3",
    isTrending: false,
  },
  {
    id: "track-4",
    title: "Dreamy Piano",
    artist: "Keys",
    duration: 60,
    bpm: 72,
    genre: "Classical",
    previewUrl: "/audio/dreamy-piano-preview.mp3",
    fullUrl: "/audio/dreamy-piano.mp3",
    isTrending: false,
  },
  {
    id: "track-5",
    title: "Funk It Up",
    artist: "GrooveMaster",
    duration: 20,
    bpm: 110,
    genre: "Funk",
    previewUrl: "/audio/funk-it-up-preview.mp3",
    fullUrl: "/audio/funk-it-up.mp3",
    isTrending: true,
  },
  {
    id: "track-6",
    title: "Neon Lights",
    artist: "RetroFuture",
    duration: 30,
    bpm: 120,
    genre: "Synthwave",
    previewUrl: "/audio/neon-lights-preview.mp3",
    fullUrl: "/audio/neon-lights.mp3",
    isTrending: true,
  },
];

export const SAMPLE_TEMPLATES: VideoTemplate[] = [
  {
    id: "tpl-1",
    title: "Galaxy Brain",
    description: "Your idea expanding into the universe",
    thumbnailUrl: "/images/templates/galaxy-brain.jpg",
    prompt: "A brain made of stars expanding into a colorful galaxy",
    effect: "explode",
    aspectRatio: "9:16",
    category: "Trending",
    usageCount: 15420,
    isTrending: true,
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "tpl-2",
    title: "Ice Queen",
    description: "Everything freezes in stunning crystal",
    thumbnailUrl: "/images/templates/ice-queen.jpg",
    prompt:
      "A person standing as ice crystals spread from their hands freezing everything",
    effect: "freeze",
    aspectRatio: "9:16",
    category: "Fantasy",
    usageCount: 8930,
    isTrending: true,
    createdAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "tpl-3",
    title: "Pixel Nostalgia",
    description: "Transform into 8-bit retro game style",
    thumbnailUrl: "/images/templates/pixel-nostalgia.jpg",
    prompt: "Scene transforming from realistic to 8-bit pixel art game style",
    effect: "pixelate",
    aspectRatio: "16:9",
    category: "Retro",
    usageCount: 6200,
    isTrending: false,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "tpl-4",
    title: "Melting Reality",
    description: "The world drips away like paint",
    thumbnailUrl: "/images/templates/melting-reality.jpg",
    prompt:
      "A city scene where everything starts melting like Salvador Dali painting",
    effect: "melt",
    aspectRatio: "1:1",
    category: "Art",
    usageCount: 12300,
    isTrending: true,
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "tpl-5",
    title: "Butterfly Effect",
    description: "Watch anything transform beautifully",
    thumbnailUrl: "/images/templates/butterfly-effect.jpg",
    prompt:
      "An object breaking apart and reforming as a swarm of colorful butterflies",
    effect: "transform",
    aspectRatio: "9:16",
    category: "Nature",
    usageCount: 9870,
    isTrending: true,
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "tpl-6",
    title: "Neon City",
    description: "Cyberpunk glow-up for any scene",
    thumbnailUrl: "/images/templates/neon-city.jpg",
    prompt:
      "A street scene with neon outlines appearing on everything, cyberpunk style",
    effect: "neon",
    aspectRatio: "16:9",
    category: "Sci-Fi",
    usageCount: 7450,
    isTrending: false,
    createdAt: "2024-01-03T00:00:00Z",
  },
];

export const SAMPLE_MEME_TEMPLATES: MemeTemplate[] = [
  {
    id: "meme-1",
    title: "This is Fine",
    thumbnailUrl: "/images/memes/this-is-fine.jpg",
    topText: "When the deadline is tomorrow",
    bottomText: "This is fine",
    effect: "explode",
    category: "Relatable",
  },
  {
    id: "meme-2",
    title: "Brain Expand",
    thumbnailUrl: "/images/memes/brain-expand.jpg",
    topText: "Small brain: Normal solution",
    bottomText: "Galaxy brain: Overcomplicated solution",
    effect: "inflate",
    category: "Funny",
  },
  {
    id: "meme-3",
    title: "Distracted",
    thumbnailUrl: "/images/memes/distracted.jpg",
    topText: "Me with my responsibilities",
    bottomText: "That new shiny thing",
    effect: "dissolve",
    category: "Relatable",
  },
  {
    id: "meme-4",
    title: "Drip Too Hard",
    thumbnailUrl: "/images/memes/drip.jpg",
    topText: "When the outfit hits different",
    bottomText: "Drip too hard",
    effect: "melt",
    category: "Fashion",
  },
];

export const SAMPLE_VIDEOS: VideoProject[] = [
  {
    id: "vid-1",
    userId: "user-1",
    title: "Galaxy Brain Moment",
    prompt: "A brain made of stars expanding into the universe",
    mode: "prompt",
    effect: "explode",
    aspectRatio: "9:16",
    duration: 5,
    status: "ready",
    videoUrl: "/videos/sample-1.mp4",
    thumbnailUrl: "/images/thumbnails/galaxy.jpg",
    musicTrackId: "track-1",
    isPublic: true,
    likes: 2430,
    remixes: 156,
    views: 45200,
    templateId: "tpl-1",
    sourceImageUrl: null,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "vid-2",
    userId: "user-2",
    title: "Melting Cityscape",
    prompt: "New York City melting like ice cream on a summer day",
    mode: "scene",
    effect: "melt",
    aspectRatio: "16:9",
    duration: 10,
    status: "ready",
    videoUrl: "/videos/sample-2.mp4",
    thumbnailUrl: "/images/thumbnails/melt-city.jpg",
    musicTrackId: "track-2",
    isPublic: true,
    likes: 1890,
    remixes: 89,
    views: 32100,
    templateId: null,
    sourceImageUrl: null,
    createdAt: "2024-01-14T15:20:00Z",
    updatedAt: "2024-01-14T15:20:00Z",
  },
  {
    id: "vid-3",
    userId: "user-3",
    title: "Frozen Rose",
    prompt: "A red rose slowly freezing with ice crystals",
    mode: "prompt",
    effect: "freeze",
    aspectRatio: "1:1",
    duration: 5,
    status: "ready",
    videoUrl: "/videos/sample-3.mp4",
    thumbnailUrl: "/images/thumbnails/frozen-rose.jpg",
    musicTrackId: null,
    isPublic: true,
    likes: 3210,
    remixes: 234,
    views: 67800,
    templateId: null,
    sourceImageUrl: null,
    createdAt: "2024-01-13T08:45:00Z",
    updatedAt: "2024-01-13T08:45:00Z",
  },
];

import type { VideoProject } from "@/types";
